#!/usr/bin/env python3
"""Remap standard cell SPICE port orders for post-extraction simulation.

The Magic-extracted netlist contains black-box stubs with port orders from the
layout.  The PDK's transistor-level SPICE models use different port orders from
the schematic.  Since SPICE subcircuit instantiation is positional, we must
produce cell definitions whose port order matches the extracted stubs.

Usage:
    python3 remap_spice_ports.py <extracted.spice> <pdk_stdcell.spice> <output.spice>
"""

import sys


def parse_subckt_header(line, continuation_lines):
    """Parse a .subckt line (possibly with + continuations) into (name, [ports])."""
    full = line.strip()
    for cl in continuation_lines:
        full += " " + cl.strip().lstrip("+").strip()
    parts = full.split()
    # parts[0] = '.subckt', parts[1] = name, rest = ports
    return parts[1], parts[2:]


def parse_spice_subcircuits(filepath):
    """Parse a SPICE file into a dict of {name: (ports, body_lines)}.

    body_lines does NOT include the .subckt or .ends lines.
    """
    cells = {}
    with open(filepath, "r") as f:
        lines = f.readlines()

    i = 0
    while i < len(lines):
        line = lines[i]
        if line.strip().lower().startswith(".subckt"):
            # Collect continuation lines
            cont = []
            j = i + 1
            while j < len(lines) and lines[j].strip().startswith("+"):
                cont.append(lines[j])
                j += 1

            name, ports = parse_subckt_header(line, cont)

            # Collect body until .ends
            body = []
            k = j
            while k < len(lines) and not lines[k].strip().lower().startswith(".ends"):
                body.append(lines[k])
                k += 1

            cells[name] = (ports, body)
            i = k + 1
        else:
            i += 1

    return cells


def remap_cell(name, extracted_ports, pdk_ports, pdk_body):
    """Create a cell definition with extracted port order and PDK transistor body.

    The PDK body uses port names internally (e.g., VDD, VSS, A, Y), so changing
    the .subckt port order doesn't affect the body — it only changes the
    positional-to-name mapping at the interface.
    """
    lines = []
    lines.append(f".subckt {name} {' '.join(extracted_ports)}\n")
    for body_line in pdk_body:
        lines.append(body_line)
    lines.append(f".ends {name}\n")
    return lines


def main():
    if len(sys.argv) != 4:
        print(f"Usage: {sys.argv[0]} <extracted.spice> <pdk_stdcell.spice> <output.spice>")
        sys.exit(1)

    extracted_path = sys.argv[1]
    pdk_path = sys.argv[2]
    output_path = sys.argv[3]

    print(f"Parsing extracted netlist: {extracted_path}")
    extracted_cells = parse_spice_subcircuits(extracted_path)

    print(f"Parsing PDK standard cells: {pdk_path}")
    pdk_cells = parse_spice_subcircuits(pdk_path)

    # Separate the top-level design from the standard cell stubs
    top_name = None
    for name in extracted_cells:
        if name.startswith("tt_um_"):
            top_name = name
            break

    if not top_name:
        print("ERROR: Could not find top-level subcircuit (tt_um_*) in extracted netlist")
        sys.exit(1)

    stdcell_stubs = {k: v for k, v in extracted_cells.items() if k != top_name}
    top_ports, top_body = extracted_cells[top_name]

    print(f"\nTop-level: {top_name} ({len(top_ports)} ports)")
    print(f"Standard cell stubs: {len(stdcell_stubs)}")

    # Remap each standard cell
    remapped = []
    missing = []
    for cell_name, (ext_ports, _) in sorted(stdcell_stubs.items()):
        if cell_name in pdk_cells:
            pdk_ports, pdk_body = pdk_cells[cell_name]
            cell_lines = remap_cell(cell_name, ext_ports, pdk_ports, pdk_body)
            remapped.append((cell_name, cell_lines))

            # Report port order difference
            if ext_ports != pdk_ports:
                print(f"  [remapped] {cell_name}: {ext_ports} (was {pdk_ports})")
            else:
                print(f"  [ok]       {cell_name}: port order matches")
        else:
            missing.append(cell_name)
            print(f"  [missing]  {cell_name}: not found in PDK SPICE")

    if missing:
        print(f"\nWARNING: {len(missing)} cells not found in PDK SPICE: {missing}")
        print("These will be included as empty stubs (filler/decap cells are OK empty)")

    # Write output file
    with open(output_path, "w") as f:
        f.write("* Post-extraction netlist with port-remapped standard cells\n")
        f.write(f"* Generated by remap_spice_ports.py\n")
        f.write(f"* Source: {extracted_path}\n")
        f.write(f"* PDK cells: {pdk_path}\n\n")

        # Write remapped standard cell definitions
        f.write("* === Standard cell definitions (port-remapped) ===\n\n")
        for cell_name, cell_lines in remapped:
            f.writelines(cell_lines)
            f.write("\n")

        # Write empty stubs for missing cells (filler, decap, etc.)
        for cell_name in missing:
            ext_ports, _ = stdcell_stubs[cell_name]
            f.write(f"* Black-box stub (no PDK SPICE model)\n")
            f.write(f".subckt {cell_name} {' '.join(ext_ports)}\n")
            f.write(f".ends {cell_name}\n\n")

        # Write top-level extracted design (with parasitics)
        f.write("* === Extracted top-level design (with parasitic RC) ===\n\n")
        f.write(f".subckt {top_name} {' '.join(top_ports)}\n")
        for body_line in top_body:
            f.write(body_line)
        f.write(f".ends {top_name}\n")

    print(f"\nWrote {output_path}")
    print(f"  {len(remapped)} remapped cells + {len(missing)} stubs + 1 top-level")


if __name__ == "__main__":
    main()
